name: Run downloadData Daily

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Debug file paths
        run: |
          ls -R


      - name: Run the update script
        run: python downloadData.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update final.csv (wind data file) via daily script" || echo "No changes to commit"
          git push
